services:
    homepage:
        image: jordanroher/starbase-80
        ports:
            - 4173:4173
        volumes:
            - ./config.json:/app/src/config/config.json
            - ./icons:/app/public/icons # or wherever, JSON icon paths are relative to /app/public
